version: '3.5'
services:
  # server:
  #     build:
  #         context: .
  #         dockerfile: ./Dockerfile
  #         args:
  #             - http_proxy
  #             - https_proxy
  #             - no_proxy
  #     image: speleograph/server:latest
  #     ports:
  #         - '8083:8083'
  #     environment:
  #         - MONGO_URL=mongodb://127.0.0.1:27017
  mongodb:
    image: mongo:5.0.8
    ports:
      - '27017:27017'
