/**
 * @file Automatically generated by barrelsby.
 */

export * from "./category.controller";
export * from "./chapter.controller";
export * from "./chat.controller";
export * from "./course.controller";
export * from "./message.controller";
export * from "./teachRequest.controller";
export * from "./user.controller";
